name: Demo QA Test
on: push
jobs:
  cupress-run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
    - name: Cypress run
    - uses: actions/checkout@v3.4.0
    - uses: cypress-io/github-action@v5
      with:
        config-file: cypress.config.js
