name: Demo QA Test
'on':
  schedule:
    - cron: 0 11 * * 5
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.config.js
